CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(26) PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    name VARCHAR(255) NOT NULL,
    national_identity_number VARCHAR(255) UNIQUE,
    birth_place varchar(255),
    birth_date DATE,
    gender varchar(26),
    address varchar(255),
    neighborhood_community_unit varchar(255),
    village varchar(255),
    district varchar(255),
    religion varchar(255),
    marital_status varchar(255),
    profession varchar(255),
    citizenship varchar(255),
    card_valid_until DATE,
    password VARCHAR(255),
    phone_number VARCHAR(255) UNIQUE,
    personal_identification_number VARCHAR(255),
    enable_touch_id BOOLEAN DEFAULT FALSE,
    hash_touch_id VARCHAR(255),
    is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)